# Tugas Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [46]:
data = pd.read_excel('E:/Data Mining/Data_Cortex_Nuclear.xls')

## Deskripsi Data

In [47]:
data.shape

(1080, 27)

In [48]:
data.head(n=5)

,MouseID,CAMKII_N,CREB_N,ELK_N,ERK_N,GSK3B_N,JNK_N,MEK_N,TRKA_N,RSK_N,...,pCFOS_N,SYP_N,H3AcK18_N,EGR1_N,H3MeK4_N,CaNA_N,Genotype,Treatment,Behavior,class
0,309_1,0.369608,0.178944,1.866358,3.685247,1.537227,0.264526,0.319677,0.813866,0.165846,...,0.108336,0.427099,0.114783,0.131790,0.128186,1.675652,Control,Memantine,C/S,c-CS-m
1,309_2,0.356178,0.173680,1.761047,3.485287,1.509249,0.255727,0.304419,0.780504,0.157194,...,0.104315,0.441581,0.111974,0.135103,0.131119,1.743610,Control,Memantine,C/S,c-CS-m
2,309_3,0.368089,0.173905,1.765544,3.571456,1.501244,0.259614,0.311747,0.785154,0.160895,...,0.106219,0.435777,0.111883,0.133362,0.127431,1.926427,Control,Memantine,C/S,c-CS-m
3,309_4,0.362970,0.179449,1.286277,2.970137,1.419710,0.259536,0.279218,0.734492,0.162210,...,0.111262,0.391691,0.130405,0.147444,0.146901,1.700563,Control,Memantine,C/S,c-CS-m
4,309_5,0.355311,0.174836,1.324695,2.896334,1.359876,0.250705,0.273667,0.702699,0.154827,...,0.110694,0.434154,0.118481,0.140314,0.148380,1.839730,Control,Memantine,C/S,c-CS-m

In [49]:
data.tail(n=5)

,MouseID,CAMKII_N,CREB_N,ELK_N,ERK_N,GSK3B_N,JNK_N,MEK_N,TRKA_N,RSK_N,...,pCFOS_N,SYP_N,H3AcK18_N,EGR1_N,H3MeK4_N,CaNA_N,Genotype,Treatment,Behavior,class
1075,J3295_11,0.330859,0.190173,0.896430,1.822906,0.993107,0.236303,0.249205,0.641746,0.165606,...,0.183324,0.374088,0.318782,0.204660,0.328327,1.364823,Ts65Dn,Saline,S/C,t-SC-s
1076,J3295_12,0.338610,0.181223,0.958879,1.879913,0.974891,0.245451,0.262191,0.693595,0.191594,...,0.175674,0.375259,0.325639,0.200415,0.293435,1.364478,Ts65Dn,Saline,S/C,t-SC-s
1077,J3295_13,0.326981,0.212631,0.762892,1.425262,0.818199,0.216741,0.235426,0.559043,0.168161,...,0.158296,0.422121,0.321306,0.229193,0.355213,1.430825,Ts65Dn,Saline,S/C,t-SC-s
1078,J3295_14,0.313149,0.172252,0.781893,1.558887,0.872820,0.238095,0.270429,0.585146,0.163433,...,0.196296,0.397676,0.335936,0.251317,0.365353,1.404031,Ts65Dn,Saline,S/C,t-SC-s
1079,J3295_15,0.349800,0.187583,0.884735,1.785937,0.970182,0.287049,0.281709,0.666667,0.190031,...,0.187556,0.420347,0.335062,0.252995,0.365278,1.370999,Ts65Dn,Saline,S/C,t-SC-s

In [50]:
data.describe() #statistika deskriptif

,CAMKII_N,CREB_N,ELK_N,ERK_N,GSK3B_N,JNK_N,MEK_N,TRKA_N,RSK_N,APP_N,...,DSCR1_N,BAD_N,BCL2_N,pS6_N,pCFOS_N,SYP_N,H3AcK18_N,EGR1_N,H3MeK4_N,CaNA_N
count,1077.000000,1077.000000,1062.000000,1077.000000,1077.000000,1077.000000,1073.000000,1077.000000,1077.000000,1077.000000,...,1077.000000,867.000000,795.000000,1080.000000,1005.000000,1080.000000,900.000000,870.000000,810.000000,1080.000000
mean,0.363357,0.180492,1.173400,2.474492,1.172603,0.241644,0.272789,0.693180,0.168417,0.404808,...,0.585186,0.157914,0.134762,0.121521,0.131053,0.446073,0.169609,0.183135,0.205440,1.337784
std,0.052352,0.026370,0.335786,0.653397,0.244752,0.033901,0.041075,0.120825,0.028138,0.061173,...,0.100601,0.029537,0.027417,0.014276,0.023863,0.066432,0.059402,0.040406,0.055514,0.317126
min,0.212960,0.113636,0.497695,1.131796,0.151124,0.046298,0.147201,0.198743,0.107394,0.235595,...,0.155321,0.088305,0.080657,0.067254,0.085419,0.258626,0.079691,0.105537,0.101787,0.586479
25%,0.330859,0.161830,0.944435,1.991756,1.023134,0.220400,0.247096,0.617074,0.149622,0.366339,...,0.530881,0.136424,0.115554,0.110839,0.113506,0.398082,0.125848,0.155121,0.165143,1.081423
50%,0.360260,0.179580,1.096186,2.401462,1.159822,0.244947,0.273361,0.704964,0.166692,0.402039,...,0.576712,0.152313,0.129468,0.121626,0.126523,0.448459,0.158240,0.174935,0.193994,1.317441
75%,0.393851,0.195718,1.323581,2.872606,1.309673,0.263291,0.300760,0.774158,0.184533,0.441897,...,0.634433,0.174017,0.148235,0.131955,0.143652,0.490773,0.197876,0.204542,0.235215,1.585824
max,0.586245,0.319558,2.802948,5.198404,2.475751,0.387191,0.415408,1.001623,0.305136,0.632663,...,0.916429,0.282016,0.261506,0.158748,0.256529,0.759588,0.479763,0.360692,0.413903,2.129791

In [51]:
data['class'].value_counts()

c-CS-m    150
c-SC-m    150
t-SC-m    135
c-CS-s    135
t-SC-s    135
t-CS-m    134
c-SC-s    130
t-CS-s    105
Name: class, dtype: int64

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 27 columns):
MouseID       1080 non-null object
CAMKII_N      1077 non-null float64
CREB_N        1077 non-null float64
ELK_N         1062 non-null float64
ERK_N         1077 non-null float64
GSK3B_N       1077 non-null float64
JNK_N         1077 non-null float64
MEK_N         1073 non-null float64
TRKA_N        1077 non-null float64
RSK_N         1077 non-null float64
APP_N         1077 non-null float64
Bcatenin_N    1062 non-null float64
SOD1_N        1077 non-null float64
DSCR1_N       1077 non-null float64
BAD_N         867 non-null float64
BCL2_N        795 non-null float64
pS6_N         1080 non-null float64
pCFOS_N       1005 non-null float64
SYP_N         1080 non-null float64
H3AcK18_N     900 non-null float64
EGR1_N        870 non-null float64
H3MeK4_N      810 non-null float64
CaNA_N        1080 non-null float64
Genotype      1080 non-null object
Treatment     1077 non-null object
Behavior      1078 non-null object
class         1074 non-null object
dtypes: float64(22), object(5)
memory usage: 227.9+ KB

## Imputation Missing Value

In [53]:
np.sum(data.isnull()) #number of NA for each variable

MouseID         0
CAMKII_N        3
CREB_N          3
ELK_N          18
ERK_N           3
GSK3B_N         3
JNK_N           3
MEK_N           7
TRKA_N          3
RSK_N           3
APP_N           3
Bcatenin_N     18
SOD1_N          3
DSCR1_N         3
BAD_N         213
BCL2_N        285
pS6_N           0
pCFOS_N        75
SYP_N           0
H3AcK18_N     180
EGR1_N        210
H3MeK4_N      270
CaNA_N          0
Genotype        0
Treatment       3
Behavior        2
class           6
dtype: int64

In [54]:
data.isnull().sum()

MouseID         0
CAMKII_N        3
CREB_N          3
ELK_N          18
ERK_N           3
GSK3B_N         3
JNK_N           3
MEK_N           7
TRKA_N          3
RSK_N           3
APP_N           3
Bcatenin_N     18
SOD1_N          3
DSCR1_N         3
BAD_N         213
BCL2_N        285
pS6_N           0
pCFOS_N        75
SYP_N           0
H3AcK18_N     180
EGR1_N        210
H3MeK4_N      270
CaNA_N          0
Genotype        0
Treatment       3
Behavior        2
class           6
dtype: int64

In [55]:
data.isnull().sum().sum()

1317

In [56]:
#imputasi missing value data numerik
data['CAMKII_N'] = data['CAMKII_N'].fillna((data['CAMKII_N'].mean())) 
data['CREB_N'] = data['CREB_N'].fillna((data['CREB_N'].mean()))
data['ELK_N'] = data['ELK_N'].fillna((data['ELK_N'].median()))
data['ERK_N'] = data['ERK_N'].fillna((data['ERK_N'].mean()))
data['GSK3B_N'] = data['GSK3B_N'].fillna((data['GSK3B_N'].mean()))
data['JNK_N'] = data['JNK_N'].fillna((data['JNK_N'].mean()))
data['MEK_N'] = data['MEK_N'].fillna((data['MEK_N'].mean()))
data['TRKA_N'] = data['TRKA_N'].fillna((data['TRKA_N'].mean()))
data['RSK_N'] = data['RSK_N'].fillna((data['RSK_N'].mean()))
data.isnull().any()

MouseID       False
CAMKII_N      False
CREB_N        False
ELK_N         False
ERK_N         False
GSK3B_N       False
JNK_N         False
MEK_N         False
TRKA_N        False
RSK_N         False
APP_N          True
Bcatenin_N     True
SOD1_N         True
DSCR1_N        True
BAD_N          True
BCL2_N         True
pS6_N         False
pCFOS_N        True
SYP_N         False
H3AcK18_N      True
EGR1_N         True
H3MeK4_N       True
CaNA_N        False
Genotype      False
Treatment      True
Behavior       True
class          True
dtype: bool

In [58]:
# imputasi untuk data numerik yang lain
data['APP_N'] = data['APP_N'].fillna((data['APP_N'].mean())) 
data['Bcatenin_N'] = data['Bcatenin_N'].fillna((data['Bcatenin_N'].median()))
data['SOD1_N'] = data['SOD1_N'].fillna((data['SOD1_N'].median()))
data['DSCR1_N'] = data['DSCR1_N'].fillna((data['DSCR1_N'].mean()))
data['BAD_N'] = data['BAD_N'].fillna((data['BAD_N'].mean()))
data['BCL2_N'] = data['BCL2_N'].fillna((data['BCL2_N'].mean()))
data['pCFOS_N'] = data['pCFOS_N'].fillna((data['pCFOS_N'].mean()))
data['H3AcK18_N'] = data['H3AcK18_N'].fillna((data['H3AcK18_N'].mean()))
data['EGR1_N'] = data['EGR1_N'].fillna((data['EGR1_N'].mean()))
data['H3MeK4_N'] = data['H3MeK4_N'].fillna((data['H3MeK4_N'].mean()))
data.isnull().any()

MouseID       False
CAMKII_N      False
CREB_N        False
ELK_N         False
ERK_N         False
GSK3B_N       False
JNK_N         False
MEK_N         False
TRKA_N        False
RSK_N         False
APP_N         False
Bcatenin_N    False
SOD1_N        False
DSCR1_N       False
BAD_N         False
BCL2_N        False
pS6_N         False
pCFOS_N       False
SYP_N         False
H3AcK18_N     False
EGR1_N        False
H3MeK4_N      False
CaNA_N        False
Genotype      False
Treatment      True
Behavior       True
class          True
dtype: bool

In [59]:
#imputasi data kategorik dengan modus
data = data.apply(lambda x:x.fillna(x.value_counts().index[0]))
data.isnull().any()

MouseID       False
CAMKII_N      False
CREB_N        False
ELK_N         False
ERK_N         False
GSK3B_N       False
JNK_N         False
MEK_N         False
TRKA_N        False
RSK_N         False
APP_N         False
Bcatenin_N    False
SOD1_N        False
DSCR1_N       False
BAD_N         False
BCL2_N        False
pS6_N         False
pCFOS_N       False
SYP_N         False
H3AcK18_N     False
EGR1_N        False
H3MeK4_N      False
CaNA_N        False
Genotype      False
Treatment     False
Behavior      False
class         False
dtype: bool

## Encode Labels

In [60]:
from sklearn.preprocessing import LabelEncoder

In [61]:
# Encode untuk Sex, Steroid, Anaroxia, Spleen Pabable, Spiders tanpa membuat kolom baru
data['Genotype'] = LabelEncoder().fit_transform(data['Genotype'])
data['Treatment'] = LabelEncoder().fit_transform(data['Treatment'])
data['Behavior'] = LabelEncoder().fit_transform(data['Behavior'])
data['class'] = LabelEncoder().fit_transform(data['class'])
data.head()

,MouseID,CAMKII_N,CREB_N,ELK_N,ERK_N,GSK3B_N,JNK_N,MEK_N,TRKA_N,RSK_N,...,pCFOS_N,SYP_N,H3AcK18_N,EGR1_N,H3MeK4_N,CaNA_N,Genotype,Treatment,Behavior,class
0,309_1,0.369608,0.178944,1.866358,3.685247,1.537227,0.264526,0.319677,0.813866,0.165846,...,0.108336,0.427099,0.114783,0.131790,0.128186,1.675652,0,0,0,0
1,309_2,0.356178,0.173680,1.761047,3.485287,1.509249,0.255727,0.304419,0.780504,0.157194,...,0.104315,0.441581,0.111974,0.135103,0.131119,1.743610,0,0,0,0
2,309_3,0.368089,0.173905,1.765544,3.571456,1.501244,0.259614,0.311747,0.785154,0.160895,...,0.106219,0.435777,0.111883,0.133362,0.127431,1.926427,0,0,0,0
3,309_4,0.362970,0.179449,1.286277,2.970137,1.419710,0.259536,0.279218,0.734492,0.162210,...,0.111262,0.391691,0.130405,0.147444,0.146901,1.700563,0,0,0,0
4,309_5,0.355311,0.174836,1.324695,2.896334,1.359876,0.250705,0.273667,0.702699,0.154827,...,0.110694,0.434154,0.118481,0.140314,0.148380,1.839730,0,0,0,0

In [62]:
data.tail()

,MouseID,CAMKII_N,CREB_N,ELK_N,ERK_N,GSK3B_N,JNK_N,MEK_N,TRKA_N,RSK_N,...,pCFOS_N,SYP_N,H3AcK18_N,EGR1_N,H3MeK4_N,CaNA_N,Genotype,Treatment,Behavior,class
1075,J3295_11,0.330859,0.190173,0.896430,1.822906,0.993107,0.236303,0.249205,0.641746,0.165606,...,0.183324,0.374088,0.318782,0.204660,0.328327,1.364823,1,1,1,7
1076,J3295_12,0.338610,0.181223,0.958879,1.879913,0.974891,0.245451,0.262191,0.693595,0.191594,...,0.175674,0.375259,0.325639,0.200415,0.293435,1.364478,1,1,1,7
1077,J3295_13,0.326981,0.212631,0.762892,1.425262,0.818199,0.216741,0.235426,0.559043,0.168161,...,0.158296,0.422121,0.321306,0.229193,0.355213,1.430825,1,1,1,7
1078,J3295_14,0.313149,0.172252,0.781893,1.558887,0.872820,0.238095,0.270429,0.585146,0.163433,...,0.196296,0.397676,0.335936,0.251317,0.365353,1.404031,1,1,1,7
1079,J3295_15,0.349800,0.187583,0.884735,1.785937,0.970182,0.287049,0.281709,0.666667,0.190031,...,0.187556,0.420347,0.335062,0.252995,0.365278,1.370999,1,1,1,7

## Standardize

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
data['CAMKII_N'] = StandardScaler().fit(data[['CAMKII_N']]).transform(data[['CAMKII_N']])
data['CREB_N'] = StandardScaler().fit(data[['CREB_N']]).transform(data[['CREB_N']])
data['ELK_N'] = StandardScaler().fit(data[['ELK_N']]).transform(data[['ELK_N']])
data['ERK_N'] = StandardScaler().fit(data[['ERK_N']]).transform(data[['ERK_N']])
data['GSK3B_N'] = StandardScaler().fit(data[['GSK3B_N']]).transform(data[['GSK3B_N']])
data['JNK_N'] = StandardScaler().fit(data[['JNK_N']]).transform(data[['JNK_N']])
data['MEK_N'] = StandardScaler().fit(data[['MEK_N']]).transform(data[['MEK_N']])
data['TRKA_N'] = StandardScaler().fit(data[['TRKA_N']]).transform(data[['TRKA_N']])
data['RSK_N'] = StandardScaler().fit(data[['RSK_N']]).transform(data[['RSK_N']])
data['APP_N'] = StandardScaler().fit(data[['APP_N']]).transform(data[['APP_N']])
data['Bcatenin_N'] = StandardScaler().fit(data[['Bcatenin_N']]).transform(data[['Bcatenin_N']])
data['SOD1_N'] = StandardScaler().fit(data[['SOD1_N']]).transform(data[['SOD1_N']])
data['DSCR1_N'] = StandardScaler().fit(data[['DSCR1_N']]).transform(data[['DSCR1_N']])
data['BAD_N'] = StandardScaler().fit(data[['BAD_N']]).transform(data[['BAD_N']])
data['BCL2_N'] = StandardScaler().fit(data[['BCL2_N']]).transform(data[['BCL2_N']])
data['pCFOS_N'] = StandardScaler().fit(data[['pCFOS_N']]).transform(data[['pCFOS_N']])
data['H3AcK18_N'] = StandardScaler().fit(data[['H3AcK18_N']]).transform(data[['H3AcK18_N']])
data['EGR1_N'] = StandardScaler().fit(data[['EGR1_N']]).transform(data[['EGR1_N']])
data['H3MeK4_N'] = StandardScaler().fit(data[['H3MeK4_N']]).transform(data[['H3MeK4_N']])
data.head()

,MouseID,CAMKII_N,CREB_N,ELK_N,ERK_N,GSK3B_N,JNK_N,MEK_N,TRKA_N,RSK_N,...,pCFOS_N,SYP_N,H3AcK18_N,EGR1_N,H3MeK4_N,CaNA_N,Genotype,Treatment,Behavior,class
0,309_1,0.119633,-0.058786,2.085036,1.856458,1.492537,0.676225,1.145759,1.000709,-0.091534,...,-0.987371,0.427099,-1.011615,-1.416624,-1.607891,1.675652,0,0,0,0
1,309_2,-0.137387,-0.258798,1.768753,1.549858,1.378016,0.416185,0.772906,0.724076,-0.399609,...,-1.162114,0.441581,-1.063458,-1.325218,-1.546844,1.743610,0,0,0,0
2,309_3,0.090559,-0.250248,1.782261,1.681981,1.345245,0.531041,0.951974,0.762632,-0.267804,...,-1.079366,0.435777,-1.065130,-1.373257,-1.623595,1.926427,0,0,0,0
3,309_4,-0.007399,-0.039614,0.342870,0.759976,1.011497,0.528743,0.157103,0.342551,-0.221000,...,-0.860192,0.391691,-0.723367,-0.984718,-1.218364,1.700563,0,0,0,0
4,309_5,-0.153972,-0.214886,0.458251,0.646813,0.766579,0.267771,0.021461,0.078934,-0.483854,...,-0.884881,0.434154,-0.943378,-1.181435,-1.187585,1.839730,0,0,0,0

# Normalize

In [65]:
from sklearn.preprocessing import Normalizer

In [66]:
data['CAMKII_N'] = Normalizer().fit(data[['CAMKII_N']]).transform(data[['CAMKII_N']])
data['CREB_N'] = Normalizer().fit(data[['CREB_N']]).transform(data[['CREB_N']])
data['ELK_N'] = Normalizer().fit(data[['ELK_N']]).transform(data[['ELK_N']])
data['ERK_N'] = Normalizer().fit(data[['ERK_N']]).transform(data[['ERK_N']])
data['GSK3B_N'] = Normalizer().fit(data[['GSK3B_N']]).transform(data[['GSK3B_N']])
data['JNK_N'] = Normalizer().fit(data[['JNK_N']]).transform(data[['JNK_N']])
data['MEK_N'] = Normalizer().fit(data[['MEK_N']]).transform(data[['MEK_N']])
data['TRKA_N'] = Normalizer().fit(data[['TRKA_N']]).transform(data[['TRKA_N']])
data['RSK_N'] = Normalizer().fit(data[['RSK_N']]).transform(data[['RSK_N']])
data['APP_N'] = Normalizer().fit(data[['APP_N']]).transform(data[['APP_N']])
data['Bcatenin_N'] = Normalizer().fit(data[['Bcatenin_N']]).transform(data[['Bcatenin_N']])
data['SOD1_N'] = Normalizer().fit(data[['SOD1_N']]).transform(data[['SOD1_N']])
data['DSCR1_N'] = Normalizer().fit(data[['DSCR1_N']]).transform(data[['DSCR1_N']])
data['BAD_N'] = Normalizer().fit(data[['BAD_N']]).transform(data[['BAD_N']])
data['BCL2_N'] = Normalizer().fit(data[['BCL2_N']]).transform(data[['BCL2_N']])
data['pCFOS_N'] = Normalizer().fit(data[['pCFOS_N']]).transform(data[['pCFOS_N']])
data['H3AcK18_N'] = Normalizer().fit(data[['H3AcK18_N']]).transform(data[['H3AcK18_N']])
data['EGR1_N'] = Normalizer().fit(data[['EGR1_N']]).transform(data[['EGR1_N']])
data['H3MeK4_N'] = Normalizer().fit(data[['H3MeK4_N']]).transform(data[['H3MeK4_N']])

In [67]:
data.head()

,MouseID,CAMKII_N,CREB_N,ELK_N,ERK_N,GSK3B_N,JNK_N,MEK_N,TRKA_N,RSK_N,...,pCFOS_N,SYP_N,H3AcK18_N,EGR1_N,H3MeK4_N,CaNA_N,Genotype,Treatment,Behavior,class
0,309_1,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,...,-1.0,0.427099,-1.0,-1.0,-1.0,1.675652,0,0,0,0
1,309_2,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,...,-1.0,0.441581,-1.0,-1.0,-1.0,1.743610,0,0,0,0
2,309_3,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,...,-1.0,0.435777,-1.0,-1.0,-1.0,1.926427,0,0,0,0
3,309_4,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,...,-1.0,0.391691,-1.0,-1.0,-1.0,1.700563,0,0,0,0
4,309_5,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,...,-1.0,0.434154,-1.0,-1.0,-1.0,1.839730,0,0,0,0