# Data Integration

In [2]:
### Data integration
import pandas as pd
import numpy as np

In [3]:
#load data
#data berasalh dari UCI, student performance data set
siswa = pd.read_csv (r'E:\Data Mining\student-mat.csv', sep = ';')
kategori = pd.read_csv(r'E:\Data Mining\student-categoric.csv', sep =';')
siswa

,id,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,absences
0,1,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,6
1,2,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,4
2,3,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,10
3,4,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,2
4,5,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,4
5,6,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother,1,2,10
6,7,GP,M,16,U,LE3,T,2,2,other,other,home,mother,1,2,0
7,8,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother,2,2,6
8,9,GP,M,15,U,LE3,A,3,2,services,other,home,mother,1,2,0
9,10,GP,M,15,U,GT3,T,3,4,other,other,home,mother,1,2,0
10,11,GP,F,15,U,GT3,T,4,4,teacher,health,reputation,mother,1,2,0
11,12,GP,F,15,U,GT3,T,2,1,services,other,reputation,father,3,3,4
12,13,GP,M,15,U,LE3,T,4,4,health,services,course,father,1,1,2
13,14,GP,M,15,U,GT3,T,4,3,teacher,other,course,mother,2,2,2
14,15,GP,M,15,U,GT3,A,2,2,other,other,home,other,1,3,0
15,16,GP,F,16,U,GT3,T,4,4,health,other,home,mother,1,1,4
16,17,GP,F,16,U,GT3,T,4,4,services,services,reputation,mother,1,3,6
17,18,GP,F,16,U,GT3,T,3,3,other,other,reputation,mother,3,2,4
18,19,GP,M,17,U,GT3,T,3,2,services,services,course,mother,1,1,16
19,20,GP,M,16,U,LE3,T,4,3,health,other,home,father,1,1,4
20,21,GP,M,15,U,GT3,T,4,3,teacher,other,reputation,mother,1,2,0
21,22,GP,M,15,U,GT3,T,4,4,health,health,other,father,1,1,0
22,23,GP,M,16,U,LE3,T,4,2,teacher,other,course,mother,1,2,2
23,24,GP,M,16,U,LE3,T,2,2,other,other,reputation,mother,2,2,0
24,25,GP,F,15,R,GT3,T,2,4,services,health,course,mother,1,3,2
25,26,GP,F,16,U,GT3,T,2,2,services,services,home,mother,1,1,14
26,27,GP,M,15,U,GT3,T,2,2,other,other,home,mother,1,1,2
27,28,GP,M,15,U,GT3,T,4,2,health,services,other,mother,1,1,4
28,29,GP,M,16,U,LE3,A,3,4,services,other,home,mother,1,2,4
29,30,GP,M,16,U,GT3,T,4,4,teacher,teacher,home,mother,1,2,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,366,MS,M,18,R,GT3,T,1,3,at_home,other,course,mother,2,2,4
366,367,MS,M,18,U,LE3,T,4,4,teacher,services,other,mother,2,3,0
367,368,MS,F,17,R,GT3,T,1,1,other,services,reputation,mother,3,1,0
368,369,MS,F,18,U,GT3,T,2,3,at_home,services,course,father,2,1,0
369,370,MS,F,18,R,GT3,T,4,4,other,teacher,other,father,3,2,10
370,371,MS,F,19,U,LE3,T,3,2,services,services,home,other,2,2,4
371,372,MS,M,18,R,LE3,T,1,2,at_home,services,other,father,3,1,3
372,373,MS,F,17,U,GT3,T,2,2,other,at_home,home,mother,1,3,8
373,374,MS,F,17,R,GT3,T,1,2,other,other,course,mother,1,1,14
374,375,MS,F,18,R,LE3,T,4,4,other,other,reputation,mother,2,3,0
375,376,MS,F,18,R,GT3,T,1,1,other,other,home,mother,4,3,2
376,377,MS,F,20,U,GT3,T,4,2,health,other,course,other,2,3,4
377,378,MS,F,18,R,LE3,T,4,4,teacher,services,course,mother,1,2,4
378,379,MS,F,18,U,GT3,T,3,3,other,other,home,mother,1,2,0
379,380,MS,F,17,R,GT3,T,3,1,at_home,other,reputation,mother,1,2,17
380,381,MS,M,18,U,GT3,T,4,4,teacher,teacher,home,father,1,2,4
381,382,MS,M,18,R,GT3,T,2,1,other,other,other,mother,2,1,5
382,383,MS,M,17,U,GT3,T,2,3,other,services,home,father,2,2,2
383,384,MS,M,19,R,GT3,T,1,1,other,services,other,mother,2,1,0
384,385,MS,M,18,R,GT3,T,4,2,other,other,home,father,2,1,14
385,386,MS,F,18,R,GT3,T,2,2,at_home,other,other,mother,2,3,2
386,387,MS,F,18,R,GT3,T,4,4,teacher,at_home,reputation,mother,3,1,7
387,388,MS,F,19,R,GT3,T,2,3,services,other,course,mother,1,3,0
388,389,MS,F,18,U,LE3,T,3,1,teacher,services,course,mother,1,2,0
389,390,MS,F,18,U,GT3,T,1,1,other,other,course,mother,2,2,0
390,391,MS,M,20,U,LE3,A,2,2,services,services,course,other,1,2,11
391,392,MS,M,17,U,LE3,T,3,1,services,services,course,mother,2,1,3
392,393,MS,M,21,R,GT3,T,1,1,other,other,course,other,1,1,3
393,394,MS,M,18,R,LE3,T,3,2,services,other,course,mother,3,1,0
394,395,MS,M,19,U,LE3,T,1,1,other,at_home,course,father,1,1,5

In [4]:
siswa.head()

,id,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,absences
0,1,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,6
1,2,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,4
2,3,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,10
3,4,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,2
4,5,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,4

In [6]:
kategori

,id,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health
0,1,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3
1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3
2,3,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3
3,4,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5
4,5,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5
5,6,0,no,yes,yes,yes,yes,yes,yes,no,5,4,2,1,2,5
6,7,0,no,no,no,no,yes,yes,yes,no,4,4,4,1,1,3
7,8,0,yes,yes,no,no,yes,yes,no,no,4,1,4,1,1,1
8,9,0,no,yes,yes,no,yes,yes,yes,no,4,2,2,1,1,1
9,10,0,no,yes,yes,yes,yes,yes,yes,no,5,5,1,1,1,5
10,11,0,no,yes,yes,no,yes,yes,yes,no,3,3,3,1,2,2
11,12,0,no,yes,no,yes,yes,yes,yes,no,5,2,2,1,1,4
12,13,0,no,yes,yes,yes,yes,yes,yes,no,4,3,3,1,3,5
13,14,0,no,yes,yes,no,yes,yes,yes,no,5,4,3,1,2,3
14,15,0,no,yes,no,no,yes,yes,yes,yes,4,5,2,1,1,3
15,16,0,no,yes,no,no,yes,yes,yes,no,4,4,4,1,2,2
16,17,0,no,yes,yes,yes,yes,yes,yes,no,3,2,3,1,2,2
17,18,0,yes,yes,no,yes,yes,yes,no,no,5,3,2,1,1,4
18,19,3,no,yes,no,yes,yes,yes,yes,no,5,5,5,2,4,5
19,20,0,no,no,yes,yes,yes,yes,yes,no,3,1,3,1,3,5
20,21,0,no,no,no,no,yes,yes,yes,no,4,4,1,1,1,1
21,22,0,no,yes,yes,no,yes,yes,yes,no,5,4,2,1,1,5
22,23,0,no,no,no,yes,yes,yes,yes,no,4,5,1,1,3,5
23,24,0,no,yes,no,yes,yes,yes,yes,no,5,4,4,2,4,5
24,25,0,yes,yes,yes,yes,yes,yes,yes,no,4,3,2,1,1,5
25,26,2,no,yes,yes,no,no,yes,yes,no,1,2,2,1,3,5
26,27,0,no,yes,yes,no,yes,yes,yes,no,4,2,2,1,2,5
27,28,0,no,no,yes,no,yes,yes,yes,no,2,2,4,2,4,1
28,29,0,yes,yes,no,yes,yes,yes,yes,no,5,3,3,1,1,5
29,30,0,no,yes,yes,yes,yes,yes,yes,yes,4,4,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,366,0,no,yes,yes,no,yes,yes,no,no,3,3,4,2,4,3
366,367,0,no,no,yes,no,yes,yes,yes,yes,4,2,2,2,2,5
367,368,1,no,yes,yes,no,yes,yes,yes,yes,5,2,1,1,2,1
368,369,0,no,yes,yes,no,yes,yes,yes,yes,5,2,3,1,2,4
369,370,0,no,yes,yes,no,no,yes,yes,yes,3,2,2,4,2,5
370,371,2,no,no,no,yes,yes,yes,no,yes,3,2,2,1,1,3
371,372,0,no,yes,yes,yes,yes,no,yes,yes,4,3,3,2,3,3
372,373,0,no,no,no,yes,yes,yes,no,yes,3,4,3,1,1,3
373,374,0,no,no,no,yes,yes,yes,yes,no,3,5,5,1,3,1
374,375,0,no,no,no,no,yes,yes,yes,no,5,4,4,1,1,1
375,376,0,no,no,no,no,yes,yes,yes,no,4,3,2,1,2,4
376,377,2,no,yes,yes,no,no,yes,yes,yes,5,4,3,1,1,3
377,378,0,no,no,yes,yes,yes,yes,yes,no,5,4,3,3,4,2
378,379,0,no,no,yes,no,yes,yes,yes,yes,4,1,3,1,2,1
379,380,0,no,yes,yes,yes,no,yes,yes,no,4,5,4,2,3,1
380,381,0,no,no,yes,yes,no,yes,yes,no,3,2,4,1,4,2
381,382,0,no,no,no,yes,no,yes,yes,yes,4,4,3,1,3,5
382,383,0,no,no,no,yes,yes,yes,yes,no,4,4,3,1,1,3
383,384,1,no,no,no,no,yes,yes,no,no,4,3,2,1,3,5
384,385,1,no,no,yes,no,yes,yes,no,no,5,4,3,4,3,3
385,386,0,no,no,yes,no,yes,yes,no,no,5,3,3,1,3,4
386,387,0,no,yes,yes,yes,yes,yes,yes,yes,4,4,3,2,2,5
387,388,1,no,no,no,yes,no,yes,yes,no,5,4,2,1,2,5
388,389,0,no,yes,yes,no,yes,yes,yes,no,4,3,4,1,1,1
389,390,1,no,no,no,yes,yes,yes,no,no,1,1,1,1,1,5
390,391,2,no,yes,yes,no,yes,yes,no,no,5,5,4,4,5,4
391,392,0,no,no,no,no,no,yes,yes,no,2,4,5,3,4,2
392,393,3,no,no,no,no,no,yes,no,no,5,5,3,3,3,3
393,394,0,no,no,no,no,no,yes,yes,no,4,4,1,3,4,5
394,395,0,no,no,no,no,yes,yes,yes,no,3,2,3,3,3,5

In [7]:
kategori.head()

,id,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health
0,1,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3
1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3
2,3,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3
3,4,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5
4,5,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5

In [8]:
# merge data based on ID
data = pd.merge(siswa, kategori, on='id')
data

,id,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,...,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health
0,1,GP,F,18,U,GT3,A,4,4,at_home,...,yes,yes,no,no,4,3,4,1,1,3
1,2,GP,F,17,U,GT3,T,1,1,at_home,...,no,yes,yes,no,5,3,3,1,1,3
2,3,GP,F,15,U,LE3,T,1,1,at_home,...,yes,yes,yes,no,4,3,2,2,3,3
3,4,GP,F,15,U,GT3,T,4,2,health,...,yes,yes,yes,yes,3,2,2,1,1,5
4,5,GP,F,16,U,GT3,T,3,3,other,...,yes,yes,no,no,4,3,2,1,2,5
5,6,GP,M,16,U,LE3,T,4,3,services,...,yes,yes,yes,no,5,4,2,1,2,5
6,7,GP,M,16,U,LE3,T,2,2,other,...,yes,yes,yes,no,4,4,4,1,1,3
7,8,GP,F,17,U,GT3,A,4,4,other,...,yes,yes,no,no,4,1,4,1,1,1
8,9,GP,M,15,U,LE3,A,3,2,services,...,yes,yes,yes,no,4,2,2,1,1,1
9,10,GP,M,15,U,GT3,T,3,4,other,...,yes,yes,yes,no,5,5,1,1,1,5
10,11,GP,F,15,U,GT3,T,4,4,teacher,...,yes,yes,yes,no,3,3,3,1,2,2
11,12,GP,F,15,U,GT3,T,2,1,services,...,yes,yes,yes,no,5,2,2,1,1,4
12,13,GP,M,15,U,LE3,T,4,4,health,...,yes,yes,yes,no,4,3,3,1,3,5
13,14,GP,M,15,U,GT3,T,4,3,teacher,...,yes,yes,yes,no,5,4,3,1,2,3
14,15,GP,M,15,U,GT3,A,2,2,other,...,yes,yes,yes,yes,4,5,2,1,1,3
15,16,GP,F,16,U,GT3,T,4,4,health,...,yes,yes,yes,no,4,4,4,1,2,2
16,17,GP,F,16,U,GT3,T,4,4,services,...,yes,yes,yes,no,3,2,3,1,2,2
17,18,GP,F,16,U,GT3,T,3,3,other,...,yes,yes,no,no,5,3,2,1,1,4
18,19,GP,M,17,U,GT3,T,3,2,services,...,yes,yes,yes,no,5,5,5,2,4,5
19,20,GP,M,16,U,LE3,T,4,3,health,...,yes,yes,yes,no,3,1,3,1,3,5
20,21,GP,M,15,U,GT3,T,4,3,teacher,...,yes,yes,yes,no,4,4,1,1,1,1
21,22,GP,M,15,U,GT3,T,4,4,health,...,yes,yes,yes,no,5,4,2,1,1,5
22,23,GP,M,16,U,LE3,T,4,2,teacher,...,yes,yes,yes,no,4,5,1,1,3,5
23,24,GP,M,16,U,LE3,T,2,2,other,...,yes,yes,yes,no,5,4,4,2,4,5
24,25,GP,F,15,R,GT3,T,2,4,services,...,yes,yes,yes,no,4,3,2,1,1,5
25,26,GP,F,16,U,GT3,T,2,2,services,...,no,yes,yes,no,1,2,2,1,3,5
26,27,GP,M,15,U,GT3,T,2,2,other,...,yes,yes,yes,no,4,2,2,1,2,5
27,28,GP,M,15,U,GT3,T,4,2,health,...,yes,yes,yes,no,2,2,4,2,4,1
28,29,GP,M,16,U,LE3,A,3,4,services,...,yes,yes,yes,no,5,3,3,1,1,5
29,30,GP,M,16,U,GT3,T,4,4,teacher,...,yes,yes,yes,yes,4,4,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,366,MS,M,18,R,GT3,T,1,3,at_home,...,yes,yes,no,no,3,3,4,2,4,3
366,367,MS,M,18,U,LE3,T,4,4,teacher,...,yes,yes,yes,yes,4,2,2,2,2,5
367,368,MS,F,17,R,GT3,T,1,1,other,...,yes,yes,yes,yes,5,2,1,1,2,1
368,369,MS,F,18,U,GT3,T,2,3,at_home,...,yes,yes,yes,yes,5,2,3,1,2,4
369,370,MS,F,18,R,GT3,T,4,4,other,...,no,yes,yes,yes,3,2,2,4,2,5
370,371,MS,F,19,U,LE3,T,3,2,services,...,yes,yes,no,yes,3,2,2,1,1,3
371,372,MS,M,18,R,LE3,T,1,2,at_home,...,yes,no,yes,yes,4,3,3,2,3,3
372,373,MS,F,17,U,GT3,T,2,2,other,...,yes,yes,no,yes,3,4,3,1,1,3
373,374,MS,F,17,R,GT3,T,1,2,other,...,yes,yes,yes,no,3,5,5,1,3,1
374,375,MS,F,18,R,LE3,T,4,4,other,...,yes,yes,yes,no,5,4,4,1,1,1
375,376,MS,F,18,R,GT3,T,1,1,other,...,yes,yes,yes,no,4,3,2,1,2,4
376,377,MS,F,20,U,GT3,T,4,2,health,...,no,yes,yes,yes,5,4,3,1,1,3
377,378,MS,F,18,R,LE3,T,4,4,teacher,...,yes,yes,yes,no,5,4,3,3,4,2
378,379,MS,F,18,U,GT3,T,3,3,other,...,yes,yes,yes,yes,4,1,3,1,2,1
379,380,MS,F,17,R,GT3,T,3,1,at_home,...,no,yes,yes,no,4,5,4,2,3,1
380,381,MS,M,18,U,GT3,T,4,4,teacher,...,no,yes,yes,no,3,2,4,1,4,2
381,382,MS,M,18,R,GT3,T,2,1,other,...,no,yes,yes,yes,4,4,3,1,3,5
382,383,MS,M,17,U,GT3,T,2,3,other,...,yes,yes,yes,no,4,4,3,1,1,3
383,384,MS,M,19,R,GT3,T,1,1,other,...,yes,yes,no,no,4,3,2,1,3,5
384,385,MS,M,18,R,GT3,T,4,2,other,...,yes,yes,no,no,5,4,3,4,3,3
385,386,MS,F,18,R,GT3,T,2,2,at_home,...,yes,yes,no,no,5,3,3,1,3,4
386,387,MS,F,18,R,GT3,T,4,4,teacher,...,yes,yes,yes,yes,4,4,3,2,2,5
387,388,MS,F,19,R,GT3,T,2,3,services,...,no,yes,yes,no,5,4,2,1,2,5
388,389,MS,F,18,U,LE3,T,3,1,teacher,...,yes,yes,yes,no,4,3,4,1,1,1
389,390,MS,F,18,U,GT3,T,1,1,other,...,yes,yes,no,no,1,1,1,1,1,5
390,391,MS,M,20,U,LE3,A,2,2,services,...,yes,yes,no,no,5,5,4,4,5,4
391,392,MS,M,17,U,LE3,T,3,1,services,...,no,yes,yes,no,2,4,5,3,4,2
392,393,MS,M,21,R,GT3,T,1,1,other,...,no,yes,no,no,5,5,3,3,3,3
393,394,MS,M,18,R,LE3,T,3,2,services,...,no,yes,yes,no,4,4,1,3,4,5
394,395,MS,M,19,U,LE3,T,1,1,other,...,yes,yes,yes,no,3,2,3,3,3,5

In [32]:
# insert new colomn
# Family edu bernilai 1 jika pendidikan kedua orang tua anak kategori 4
data['Family Edu']=np.where(((data['Medu']==4) & (data['Fedu']==4)) ,'1','0')
data

,id,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,Family Edu
0,1,GP,F,18,U,GT3,A,4,4,at_home,...,yes,no,no,4,3,4,1,1,3,1
1,2,GP,F,17,U,GT3,T,1,1,at_home,...,yes,yes,no,5,3,3,1,1,3,0
2,3,GP,F,15,U,LE3,T,1,1,at_home,...,yes,yes,no,4,3,2,2,3,3,0
3,4,GP,F,15,U,GT3,T,4,2,health,...,yes,yes,yes,3,2,2,1,1,5,0
4,5,GP,F,16,U,GT3,T,3,3,other,...,yes,no,no,4,3,2,1,2,5,0
5,6,GP,M,16,U,LE3,T,4,3,services,...,yes,yes,no,5,4,2,1,2,5,0
6,7,GP,M,16,U,LE3,T,2,2,other,...,yes,yes,no,4,4,4,1,1,3,0
7,8,GP,F,17,U,GT3,A,4,4,other,...,yes,no,no,4,1,4,1,1,1,1
8,9,GP,M,15,U,LE3,A,3,2,services,...,yes,yes,no,4,2,2,1,1,1,0
9,10,GP,M,15,U,GT3,T,3,4,other,...,yes,yes,no,5,5,1,1,1,5,0
10,11,GP,F,15,U,GT3,T,4,4,teacher,...,yes,yes,no,3,3,3,1,2,2,1
11,12,GP,F,15,U,GT3,T,2,1,services,...,yes,yes,no,5,2,2,1,1,4,0
12,13,GP,M,15,U,LE3,T,4,4,health,...,yes,yes,no,4,3,3,1,3,5,1
13,14,GP,M,15,U,GT3,T,4,3,teacher,...,yes,yes,no,5,4,3,1,2,3,0
14,15,GP,M,15,U,GT3,A,2,2,other,...,yes,yes,yes,4,5,2,1,1,3,0
15,16,GP,F,16,U,GT3,T,4,4,health,...,yes,yes,no,4,4,4,1,2,2,1
16,17,GP,F,16,U,GT3,T,4,4,services,...,yes,yes,no,3,2,3,1,2,2,1
17,18,GP,F,16,U,GT3,T,3,3,other,...,yes,no,no,5,3,2,1,1,4,0
18,19,GP,M,17,U,GT3,T,3,2,services,...,yes,yes,no,5,5,5,2,4,5,0
19,20,GP,M,16,U,LE3,T,4,3,health,...,yes,yes,no,3,1,3,1,3,5,0
20,21,GP,M,15,U,GT3,T,4,3,teacher,...,yes,yes,no,4,4,1,1,1,1,0
21,22,GP,M,15,U,GT3,T,4,4,health,...,yes,yes,no,5,4,2,1,1,5,1
22,23,GP,M,16,U,LE3,T,4,2,teacher,...,yes,yes,no,4,5,1,1,3,5,0
23,24,GP,M,16,U,LE3,T,2,2,other,...,yes,yes,no,5,4,4,2,4,5,0
24,25,GP,F,15,R,GT3,T,2,4,services,...,yes,yes,no,4,3,2,1,1,5,0
25,26,GP,F,16,U,GT3,T,2,2,services,...,yes,yes,no,1,2,2,1,3,5,0
26,27,GP,M,15,U,GT3,T,2,2,other,...,yes,yes,no,4,2,2,1,2,5,0
27,28,GP,M,15,U,GT3,T,4,2,health,...,yes,yes,no,2,2,4,2,4,1,0
28,29,GP,M,16,U,LE3,A,3,4,services,...,yes,yes,no,5,3,3,1,1,5,0
29,30,GP,M,16,U,GT3,T,4,4,teacher,...,yes,yes,yes,4,4,5,5,5,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,366,MS,M,18,R,GT3,T,1,3,at_home,...,yes,no,no,3,3,4,2,4,3,0
366,367,MS,M,18,U,LE3,T,4,4,teacher,...,yes,yes,yes,4,2,2,2,2,5,1
367,368,MS,F,17,R,GT3,T,1,1,other,...,yes,yes,yes,5,2,1,1,2,1,0
368,369,MS,F,18,U,GT3,T,2,3,at_home,...,yes,yes,yes,5,2,3,1,2,4,0
369,370,MS,F,18,R,GT3,T,4,4,other,...,yes,yes,yes,3,2,2,4,2,5,1
370,371,MS,F,19,U,LE3,T,3,2,services,...,yes,no,yes,3,2,2,1,1,3,0
371,372,MS,M,18,R,LE3,T,1,2,at_home,...,no,yes,yes,4,3,3,2,3,3,0
372,373,MS,F,17,U,GT3,T,2,2,other,...,yes,no,yes,3,4,3,1,1,3,0
373,374,MS,F,17,R,GT3,T,1,2,other,...,yes,yes,no,3,5,5,1,3,1,0
374,375,MS,F,18,R,LE3,T,4,4,other,...,yes,yes,no,5,4,4,1,1,1,1
375,376,MS,F,18,R,GT3,T,1,1,other,...,yes,yes,no,4,3,2,1,2,4,0
376,377,MS,F,20,U,GT3,T,4,2,health,...,yes,yes,yes,5,4,3,1,1,3,0
377,378,MS,F,18,R,LE3,T,4,4,teacher,...,yes,yes,no,5,4,3,3,4,2,1
378,379,MS,F,18,U,GT3,T,3,3,other,...,yes,yes,yes,4,1,3,1,2,1,0
379,380,MS,F,17,R,GT3,T,3,1,at_home,...,yes,yes,no,4,5,4,2,3,1,0
380,381,MS,M,18,U,GT3,T,4,4,teacher,...,yes,yes,no,3,2,4,1,4,2,1
381,382,MS,M,18,R,GT3,T,2,1,other,...,yes,yes,yes,4,4,3,1,3,5,0
382,383,MS,M,17,U,GT3,T,2,3,other,...,yes,yes,no,4,4,3,1,1,3,0
383,384,MS,M,19,R,GT3,T,1,1,other,...,yes,no,no,4,3,2,1,3,5,0
384,385,MS,M,18,R,GT3,T,4,2,other,...,yes,no,no,5,4,3,4,3,3,0
385,386,MS,F,18,R,GT3,T,2,2,at_home,...,yes,no,no,5,3,3,1,3,4,0
386,387,MS,F,18,R,GT3,T,4,4,teacher,...,yes,yes,yes,4,4,3,2,2,5,1
387,388,MS,F,19,R,GT3,T,2,3,services,...,yes,yes,no,5,4,2,1,2,5,0
388,389,MS,F,18,U,LE3,T,3,1,teacher,...,yes,yes,no,4,3,4,1,1,1,0
389,390,MS,F,18,U,GT3,T,1,1,other,...,yes,no,no,1,1,1,1,1,5,0
390,391,MS,M,20,U,LE3,A,2,2,services,...,yes,no,no,5,5,4,4,5,4,0
391,392,MS,M,17,U,LE3,T,3,1,services,...,yes,yes,no,2,4,5,3,4,2,0
392,393,MS,M,21,R,GT3,T,1,1,other,...,yes,no,no,5,5,3,3,3,3,0
393,394,MS,M,18,R,LE3,T,3,2,services,...,yes,yes,no,4,4,1,3,4,5,0
394,395,MS,M,19,U,LE3,T,1,1,other,...,yes,yes,no,3,2,3,3,3,5,0

In [33]:
# delete colomn
data1 = data.drop(['nursery','higher','internet'], axis=1)
data1

,id,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,...,paid,activities,romantic,famrel,freetime,goout,Dalc,Walc,health,Family Edu
0,1,GP,F,18,U,GT3,A,4,4,at_home,...,no,no,no,4,3,4,1,1,3,1
1,2,GP,F,17,U,GT3,T,1,1,at_home,...,no,no,no,5,3,3,1,1,3,0
2,3,GP,F,15,U,LE3,T,1,1,at_home,...,yes,no,no,4,3,2,2,3,3,0
3,4,GP,F,15,U,GT3,T,4,2,health,...,yes,yes,yes,3,2,2,1,1,5,0
4,5,GP,F,16,U,GT3,T,3,3,other,...,yes,no,no,4,3,2,1,2,5,0
5,6,GP,M,16,U,LE3,T,4,3,services,...,yes,yes,no,5,4,2,1,2,5,0
6,7,GP,M,16,U,LE3,T,2,2,other,...,no,no,no,4,4,4,1,1,3,0
7,8,GP,F,17,U,GT3,A,4,4,other,...,no,no,no,4,1,4,1,1,1,1
8,9,GP,M,15,U,LE3,A,3,2,services,...,yes,no,no,4,2,2,1,1,1,0
9,10,GP,M,15,U,GT3,T,3,4,other,...,yes,yes,no,5,5,1,1,1,5,0
10,11,GP,F,15,U,GT3,T,4,4,teacher,...,yes,no,no,3,3,3,1,2,2,1
11,12,GP,F,15,U,GT3,T,2,1,services,...,no,yes,no,5,2,2,1,1,4,0
12,13,GP,M,15,U,LE3,T,4,4,health,...,yes,yes,no,4,3,3,1,3,5,1
13,14,GP,M,15,U,GT3,T,4,3,teacher,...,yes,no,no,5,4,3,1,2,3,0
14,15,GP,M,15,U,GT3,A,2,2,other,...,no,no,yes,4,5,2,1,1,3,0
15,16,GP,F,16,U,GT3,T,4,4,health,...,no,no,no,4,4,4,1,2,2,1
16,17,GP,F,16,U,GT3,T,4,4,services,...,yes,yes,no,3,2,3,1,2,2,1
17,18,GP,F,16,U,GT3,T,3,3,other,...,no,yes,no,5,3,2,1,1,4,0
18,19,GP,M,17,U,GT3,T,3,2,services,...,no,yes,no,5,5,5,2,4,5,0
19,20,GP,M,16,U,LE3,T,4,3,health,...,yes,yes,no,3,1,3,1,3,5,0
20,21,GP,M,15,U,GT3,T,4,3,teacher,...,no,no,no,4,4,1,1,1,1,0
21,22,GP,M,15,U,GT3,T,4,4,health,...,yes,no,no,5,4,2,1,1,5,1
22,23,GP,M,16,U,LE3,T,4,2,teacher,...,no,yes,no,4,5,1,1,3,5,0
23,24,GP,M,16,U,LE3,T,2,2,other,...,no,yes,no,5,4,4,2,4,5,0
24,25,GP,F,15,R,GT3,T,2,4,services,...,yes,yes,no,4,3,2,1,1,5,0
25,26,GP,F,16,U,GT3,T,2,2,services,...,yes,no,no,1,2,2,1,3,5,0
26,27,GP,M,15,U,GT3,T,2,2,other,...,yes,no,no,4,2,2,1,2,5,0
27,28,GP,M,15,U,GT3,T,4,2,health,...,yes,no,no,2,2,4,2,4,1,0
28,29,GP,M,16,U,LE3,A,3,4,services,...,no,yes,no,5,3,3,1,1,5,0
29,30,GP,M,16,U,GT3,T,4,4,teacher,...,yes,yes,yes,4,4,5,5,5,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,366,MS,M,18,R,GT3,T,1,3,at_home,...,yes,no,no,3,3,4,2,4,3,0
366,367,MS,M,18,U,LE3,T,4,4,teacher,...,yes,no,yes,4,2,2,2,2,5,1
367,368,MS,F,17,R,GT3,T,1,1,other,...,yes,no,yes,5,2,1,1,2,1,0
368,369,MS,F,18,U,GT3,T,2,3,at_home,...,yes,no,yes,5,2,3,1,2,4,0
369,370,MS,F,18,R,GT3,T,4,4,other,...,yes,no,yes,3,2,2,4,2,5,1
370,371,MS,F,19,U,LE3,T,3,2,services,...,no,yes,yes,3,2,2,1,1,3,0
371,372,MS,M,18,R,LE3,T,1,2,at_home,...,yes,yes,yes,4,3,3,2,3,3,0
372,373,MS,F,17,U,GT3,T,2,2,other,...,no,yes,yes,3,4,3,1,1,3,0
373,374,MS,F,17,R,GT3,T,1,2,other,...,no,yes,no,3,5,5,1,3,1,0
374,375,MS,F,18,R,LE3,T,4,4,other,...,no,no,no,5,4,4,1,1,1,1
375,376,MS,F,18,R,GT3,T,1,1,other,...,no,no,no,4,3,2,1,2,4,0
376,377,MS,F,20,U,GT3,T,4,2,health,...,yes,no,yes,5,4,3,1,1,3,0
377,378,MS,F,18,R,LE3,T,4,4,teacher,...,yes,yes,no,5,4,3,3,4,2,1
378,379,MS,F,18,U,GT3,T,3,3,other,...,yes,no,yes,4,1,3,1,2,1,0
379,380,MS,F,17,R,GT3,T,3,1,at_home,...,yes,yes,no,4,5,4,2,3,1,0
380,381,MS,M,18,U,GT3,T,4,4,teacher,...,yes,yes,no,3,2,4,1,4,2,1
381,382,MS,M,18,R,GT3,T,2,1,other,...,no,yes,yes,4,4,3,1,3,5,0
382,383,MS,M,17,U,GT3,T,2,3,other,...,no,yes,no,4,4,3,1,1,3,0
383,384,MS,M,19,R,GT3,T,1,1,other,...,no,no,no,4,3,2,1,3,5,0
384,385,MS,M,18,R,GT3,T,4,2,other,...,yes,no,no,5,4,3,4,3,3,0
385,386,MS,F,18,R,GT3,T,2,2,at_home,...,yes,no,no,5,3,3,1,3,4,0
386,387,MS,F,18,R,GT3,T,4,4,teacher,...,yes,yes,yes,4,4,3,2,2,5,1
387,388,MS,F,19,R,GT3,T,2,3,services,...,no,yes,no,5,4,2,1,2,5,0
388,389,MS,F,18,U,LE3,T,3,1,teacher,...,yes,no,no,4,3,4,1,1,1,0
389,390,MS,F,18,U,GT3,T,1,1,other,...,no,yes,no,1,1,1,1,1,5,0
390,391,MS,M,20,U,LE3,A,2,2,services,...,yes,no,no,5,5,4,4,5,4,0
391,392,MS,M,17,U,LE3,T,3,1,services,...,no,no,no,2,4,5,3,4,2,0
392,393,MS,M,21,R,GT3,T,1,1,other,...,no,no,no,5,5,3,3,3,3,0
393,394,MS,M,18,R,LE3,T,3,2,services,...,no,no,no,4,4,1,3,4,5,0
394,395,MS,M,19,U,LE3,T,1,1,other,...,no,no,no,3,2,3,3,3,5,0

In [34]:
# Drop baris ke-300 awal
a=list(range(301))
data2 = data.drop(a)
data2

,id,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,Family Edu
301,302,GP,M,17,U,LE3,T,4,4,other,...,yes,yes,no,4,1,1,2,2,5,1
302,303,GP,F,17,U,GT3,T,4,2,other,...,yes,yes,no,4,3,3,1,1,3,0
303,304,GP,F,17,U,GT3,T,3,2,health,...,yes,yes,no,5,2,2,1,2,5,0
304,305,GP,M,19,U,GT3,T,3,3,other,...,yes,yes,yes,4,4,4,1,1,3,0
305,306,GP,F,18,U,GT3,T,2,4,services,...,yes,yes,no,4,4,3,1,1,3,0
306,307,GP,M,20,U,GT3,A,3,2,services,...,yes,no,no,5,5,3,1,1,5,0
307,308,GP,M,19,U,GT3,T,4,4,teacher,...,yes,yes,yes,4,3,4,1,1,4,1
308,309,GP,M,19,R,GT3,T,3,3,other,...,yes,no,yes,4,5,3,1,2,5,0
309,310,GP,F,19,U,LE3,T,1,1,at_home,...,yes,yes,no,4,4,3,1,3,3,0
310,311,GP,F,19,U,LE3,T,1,2,services,...,yes,no,yes,4,2,4,2,2,3,0
311,312,GP,F,19,U,GT3,T,2,1,at_home,...,no,yes,yes,3,4,1,1,1,2,0
312,313,GP,M,19,U,GT3,T,1,2,other,...,yes,yes,no,4,5,2,2,2,4,0
313,314,GP,F,19,U,LE3,T,3,2,services,...,yes,yes,yes,4,2,2,1,2,1,0
314,315,GP,F,19,U,GT3,T,1,1,at_home,...,yes,yes,yes,4,1,2,1,1,3,0
315,316,GP,F,19,R,GT3,T,2,3,other,...,yes,yes,yes,4,1,2,1,1,3,0
316,317,GP,F,18,U,GT3,T,2,1,services,...,yes,yes,no,5,3,3,1,2,1,0
317,318,GP,F,18,U,GT3,T,4,3,other,...,yes,yes,yes,4,3,4,1,1,5,0
318,319,GP,F,17,R,GT3,T,3,4,at_home,...,yes,yes,no,4,3,4,2,5,5,0
319,320,GP,F,18,U,GT3,T,4,4,teacher,...,yes,yes,no,4,4,4,3,3,5,1
320,321,GP,F,17,U,GT3,A,4,3,services,...,yes,yes,yes,5,2,2,1,2,5,0
321,322,GP,F,17,U,GT3,T,2,2,other,...,yes,no,yes,4,2,2,1,1,3,0
322,323,GP,F,17,R,LE3,T,2,2,services,...,yes,yes,no,3,3,2,2,2,3,0
323,324,GP,F,17,U,GT3,T,3,1,services,...,yes,yes,no,3,4,3,2,3,5,0
324,325,GP,F,17,U,LE3,T,0,2,at_home,...,yes,yes,no,3,3,3,2,3,2,0
325,326,GP,M,18,U,GT3,T,4,4,other,...,yes,yes,no,4,3,3,2,2,3,1
326,327,GP,M,17,U,GT3,T,3,3,other,...,yes,yes,no,4,3,5,3,5,5,0
327,328,GP,M,17,R,GT3,T,2,2,services,...,yes,yes,no,4,4,5,5,5,4,0
328,329,GP,F,17,U,GT3,T,4,4,teacher,...,yes,yes,no,5,4,4,1,3,4,1
329,330,GP,F,17,U,GT3,T,4,4,teacher,...,yes,yes,yes,4,3,3,1,2,4,1
330,331,GP,M,18,U,LE3,T,2,2,other,...,yes,yes,no,4,5,5,2,4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,366,MS,M,18,R,GT3,T,1,3,at_home,...,yes,no,no,3,3,4,2,4,3,0
366,367,MS,M,18,U,LE3,T,4,4,teacher,...,yes,yes,yes,4,2,2,2,2,5,1
367,368,MS,F,17,R,GT3,T,1,1,other,...,yes,yes,yes,5,2,1,1,2,1,0
368,369,MS,F,18,U,GT3,T,2,3,at_home,...,yes,yes,yes,5,2,3,1,2,4,0
369,370,MS,F,18,R,GT3,T,4,4,other,...,yes,yes,yes,3,2,2,4,2,5,1
370,371,MS,F,19,U,LE3,T,3,2,services,...,yes,no,yes,3,2,2,1,1,3,0
371,372,MS,M,18,R,LE3,T,1,2,at_home,...,no,yes,yes,4,3,3,2,3,3,0
372,373,MS,F,17,U,GT3,T,2,2,other,...,yes,no,yes,3,4,3,1,1,3,0
373,374,MS,F,17,R,GT3,T,1,2,other,...,yes,yes,no,3,5,5,1,3,1,0
374,375,MS,F,18,R,LE3,T,4,4,other,...,yes,yes,no,5,4,4,1,1,1,1
375,376,MS,F,18,R,GT3,T,1,1,other,...,yes,yes,no,4,3,2,1,2,4,0
376,377,MS,F,20,U,GT3,T,4,2,health,...,yes,yes,yes,5,4,3,1,1,3,0
377,378,MS,F,18,R,LE3,T,4,4,teacher,...,yes,yes,no,5,4,3,3,4,2,1
378,379,MS,F,18,U,GT3,T,3,3,other,...,yes,yes,yes,4,1,3,1,2,1,0
379,380,MS,F,17,R,GT3,T,3,1,at_home,...,yes,yes,no,4,5,4,2,3,1,0
380,381,MS,M,18,U,GT3,T,4,4,teacher,...,yes,yes,no,3,2,4,1,4,2,1
381,382,MS,M,18,R,GT3,T,2,1,other,...,yes,yes,yes,4,4,3,1,3,5,0
382,383,MS,M,17,U,GT3,T,2,3,other,...,yes,yes,no,4,4,3,1,1,3,0
383,384,MS,M,19,R,GT3,T,1,1,other,...,yes,no,no,4,3,2,1,3,5,0
384,385,MS,M,18,R,GT3,T,4,2,other,...,yes,no,no,5,4,3,4,3,3,0
385,386,MS,F,18,R,GT3,T,2,2,at_home,...,yes,no,no,5,3,3,1,3,4,0
386,387,MS,F,18,R,GT3,T,4,4,teacher,...,yes,yes,yes,4,4,3,2,2,5,1
387,388,MS,F,19,R,GT3,T,2,3,services,...,yes,yes,no,5,4,2,1,2,5,0
388,389,MS,F,18,U,LE3,T,3,1,teacher,...,yes,yes,no,4,3,4,1,1,1,0
389,390,MS,F,18,U,GT3,T,1,1,other,...,yes,no,no,1,1,1,1,1,5,0
390,391,MS,M,20,U,LE3,A,2,2,services,...,yes,no,no,5,5,4,4,5,4,0
391,392,MS,M,17,U,LE3,T,3,1,services,...,yes,yes,no,2,4,5,3,4,2,0
392,393,MS,M,21,R,GT3,T,1,1,other,...,yes,no,no,5,5,3,3,3,3,0
393,394,MS,M,18,R,LE3,T,3,2,services,...,yes,yes,no,4,4,1,3,4,5,0
394,395,MS,M,19,U,LE3,T,1,1,other,...,yes,yes,no,3,2,3,3,3,5,0